FROM node:16.13-alpine

WORKDIR /usr

COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY .env.local ./
COPY .env.example ./
COPY config.json ./

RUN npm install

EXPOSE 4000

CMD ["npm", "run", "dev"]
