version: '3.8'

services:
  symposium:
    container_name: symposium
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.local
    command: npm run dev
    ports:
      - 4000:4000
    external_links:
      - db
    depends_on:
      - db
    networks:
      - app-network

  db:
    env_file: .env.local
    extends:
      file: docker-compose.db.yml
      service: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge