version: '3.8'

services:
  symposium:
    container_name: symposium
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:8080
    external_links:
      - db
    depends_on:
      - db
    networks:
      - app-network

  db:
    env_file: .env
    extends:
      file: docker-compose.db.yml
      service: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge