version: '3.8'

services:
  symposium:
    container_name: symposium
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    external_links:
      - db
    depends_on:
      - db
    networks:
      - app-network
      - app-db

  db:
    extends:
      file: docker-compose.db.yml
      service: db
    networks:
      - app-db

networks:
  app-network:
    driver: bridge
  app-db: