version: '3.8'

services:
  colloquium:
    container_name: colloquium
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 80:80
    networks:
      - app-network

networks:
    app-network:
        driver: bridge