version: '3.8'

services:
  colloquium:
    container_name: colloquium
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network
    environment:
      NODE_PORT: "80"
      NODE_ENV: "production"

networks:
    app-network:
        driver: bridge