version: '3.8'

services:
  colloquium:
    container_name: colloquium
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.local
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
    app-network:
        driver: bridge