FROM node:16.13-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY public ./public

RUN ls -a
RUN npm install --legacy-peer-deps

EXPOSE 3000

CMD ["npm", "run", "start"]
