FROM node:16.13-alpine

WORKDIR /app

COPY package.json ./
COPY src ./src
COPY public ./public
COPY .env.local ./
COPY .env.example ./

RUN ls -a
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "start"]
